import 'dotenv/config';
import express from 'express';
import cookieParser from 'cookie-parser';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import multer from 'multer';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import nodemailer from 'nodemailer';
import QRCode from 'qrcode';
import db from './db.js';

const app=express();
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));
app.set('trust proxy', 1);
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','geolocation=(), microphone=(), camera=()');next();});
const PORT=Number(process.env.PORT||3000); const JWT_SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
const uploadDir=path.resolve('uploads'); fs.mkdirSync(uploadDir,{recursive:true});
app.use(express.json({limit:'2mb'})); app.use(express.urlencoded({extended:true})); app.use(cookieParser());
app.use('/uploads',express.static(uploadDir)); app.use(express.static(path.resolve('public')));

const allowedMime=new Set(['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/jpeg','image/png','image/webp']);
const requestUpload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,'request-'+Date.now()+'-'+randomUUID()+path.extname(file.originalname).toLowerCase())}),fileFilter:(req,file,cb)=>cb(null,allowedMime.has(file.mimetype)),limits:{fileSize:Number(process.env.MAX_REQUEST_FILE_MB||10)*1024*1024}});
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,Date.now()+'-'+randomUUID()+path.extname(file.originalname).toLowerCase())}),fileFilter:(req,file,cb)=>cb(null,allowedMime.has(file.mimetype)),limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||20)*1024*1024}});
const loginLimiter=rateLimit({windowMs:15*60*1000,max:10,standardHeaders:true,legacyHeaders:false,message:{error:'ብዙ የመግቢያ ሙከራዎች ተደርገዋል። እባክዎ ቆይተው ይሞክሩ።'}});
const aiLimiter=rateLimit({windowMs:60*1000,max:20,standardHeaders:true,legacyHeaders:false,message:{error:'AI ጥያቄ ገደብ ደርሷል።'}});
function auth(req,res,next){try{const t=req.cookies.mesob_admin||''; req.admin=jwt.verify(t,JWT_SECRET); const a=db.prepare('SELECT id,email,full_name,role,institution_id,active FROM admins WHERE id=?').get(req.admin.id); if(!a||!a.active)return res.status(401).json({error:'Account disabled'}); req.admin=a; next();}catch{res.status(401).json({error:'Unauthorized'});}}
function requireRole(...roles){return (req,res,next)=>{if(roles.includes(req.admin.role)||req.admin.role==='superadmin')return next();res.status(403).json({error:'ይህን ክዋኔ ለማድረግ ፈቃድ የለዎትም።'});};}
function scopeRequests(req,res,next){if(req.admin.role==='office_staff' && req.admin.institution_id) req.officeScope=req.admin.institution_id; next();}
function signAdmin(a){return jwt.sign({id:a.id,email:a.email,role:a.role||'superadmin',institution_id:a.institution_id||null,full_name:a.full_name||''},JWT_SECRET,{expiresIn:'8h'});}
function signCitizen(c){return jwt.sign({id:c.id,phone:c.phone},JWT_SECRET,{expiresIn:'7d'});}
function citizenAuth(req,res,next){try{const t=req.cookies.mesob_citizen||''; req.citizen=jwt.verify(t,JWT_SECRET); next();}catch{res.status(401).json({error:'Citizen authentication required'});}}
function notificationConfig(){return {email:process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS,sms:!!process.env.SMS_WEBHOOK_URL};}
function makeMailer(){if(!notificationConfig().email)return null;return nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});}
async function dispatchNotification(id){const n=db.prepare('SELECT n.*, c.email citizen_email, c.full_name FROM notifications n LEFT JOIN citizens c ON c.id=n.citizen_id WHERE n.id=?').get(id);if(!n||n.status!=='Queued')return;try{if(n.channel==='email'){const mailer=makeMailer();if(!mailer||!n.citizen_email){db.prepare("UPDATE notifications SET status='Skipped' WHERE id=?").run(id);return;}await mailer.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:n.citizen_email,subject:'የእነዋሪ ከተማ ዲጂታል መሶብ — የጥያቄ ሁኔታ',text:n.message});db.prepare("UPDATE notifications SET status='Sent' WHERE id=?").run(id);}else if(n.channel==='sms'){if(!process.env.SMS_WEBHOOK_URL){db.prepare("UPDATE notifications SET status='Skipped' WHERE id=?").run(id);return;}const r=await fetch(process.env.SMS_WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.SMS_WEBHOOK_TOKEN?{Authorization:`Bearer ${process.env.SMS_WEBHOOK_TOKEN}`}:{})},body:JSON.stringify({to:n.recipient,message:n.message,reference:n.request_id})});db.prepare("UPDATE notifications SET status=? WHERE id=?").run(r.ok?'Sent':'Failed',id);} }catch(e){db.prepare("UPDATE notifications SET status='Failed' WHERE id=?").run(id);}}
function queueCitizenNotifications(requestId,citizenId,phone,message){const c=db.prepare('SELECT email FROM citizens WHERE id=?').get(citizenId);const ids=[];if(phone)ids.push(db.prepare("INSERT INTO notifications(request_id,citizen_id,channel,recipient,message) VALUES(?,?,?,?,?)").run(requestId,citizenId,'sms',phone,message).lastInsertRowid);if(c?.email)ids.push(db.prepare("INSERT INTO notifications(request_id,citizen_id,channel,recipient,message) VALUES(?,?,?,?,?)").run(requestId,citizenId,'email',c.email,message).lastInsertRowid);return ids;}
function crud(table,fields,writeRoles=['admin','editor']){
 app.get('/api/admin/'+table,auth,(req,res)=>res.json(db.prepare(`SELECT * FROM ${table} ORDER BY id DESC`).all()));
 app.post('/api/admin/'+table,auth,requireRole(...writeRoles),(req,res)=>{const vals=fields.map(f=>req.body[f]??''); const q=`INSERT INTO ${table}(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`; const r=db.prepare(q).run(...vals); res.json({id:r.lastInsertRowid});});
 app.put('/api/admin/'+table+'/:id',auth,requireRole(...writeRoles),(req,res)=>{const set=fields.map(f=>`${f}=?`).join(','); const vals=fields.map(f=>req.body[f]??''); db.prepare(`UPDATE ${table} SET ${set}, updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...vals,req.params.id); res.json({ok:true});});
 app.delete('/api/admin/'+table+'/:id',auth,requireRole(...writeRoles),(req,res)=>{db.prepare(`DELETE FROM ${table} WHERE id=?`).run(req.params.id);res.json({ok:true});});
}
app.post('/api/auth/login',loginLimiter,(req,res)=>{const {email,password}=req.body; const a=db.prepare('SELECT * FROM admins WHERE email=? AND active=1').get(email); if(!a||!bcrypt.compareSync(password,a.password_hash))return res.status(401).json({error:'የመግቢያ መረጃ ትክክል አይደለም'}); db.prepare('UPDATE admins SET last_login_at=CURRENT_TIMESTAMP WHERE id=?').run(a.id); res.cookie('mesob_admin',signAdmin(a),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*3600*1000});res.json({ok:true,admin:{id:a.id,email:a.email,full_name:a.full_name,role:a.role,institution_id:a.institution_id}});});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('mesob_admin');res.json({ok:true})});
app.get('/api/auth/me',auth,(req,res)=>res.json(req.admin));
app.post('/api/citizen/register',loginLimiter,(req,res)=>{
 const fullName=String(req.body.full_name||'').trim(), phone=String(req.body.phone||'').trim(), email=String(req.body.email||'').trim(), kebele=String(req.body.kebele||'').trim(), password=String(req.body.password||'');
 if(fullName.length<2||phone.length<7||password.length<10)return res.status(400).json({error:'ሙሉ ስም፣ ትክክለኛ ስልክ እና ቢያንስ 10 ቁምፊ የይለፍ ቃል ያስገቡ።'});
 if(db.prepare('SELECT id FROM citizens WHERE phone=?').get(phone))return res.status(409).json({error:'ይህ ስልክ ቁጥር በአካውንት ተመዝግቧል።'});
 const r=db.prepare('INSERT INTO citizens(full_name,phone,email,kebele,password_hash) VALUES(?,?,?,?,?)').run(fullName,phone,email,kebele,bcrypt.hashSync(password,12));
 const c=db.prepare('SELECT id,full_name,phone,email,kebele FROM citizens WHERE id=?').get(r.lastInsertRowid);
 res.cookie('mesob_citizen',signCitizen(c),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*24*3600*1000}); res.status(201).json({ok:true,citizen:c});
});
app.post('/api/citizen/login',loginLimiter,(req,res)=>{const phone=String(req.body.phone||'').trim(),password=String(req.body.password||'');const c=db.prepare('SELECT * FROM citizens WHERE phone=? AND active=1').get(phone);if(!c||!bcrypt.compareSync(password,c.password_hash))return res.status(401).json({error:'የስልክ ወይም የይለፍ ቃል መረጃ ትክክል አይደለም።'});res.cookie('mesob_citizen',signCitizen(c),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*24*3600*1000});res.json({ok:true,citizen:{id:c.id,full_name:c.full_name,phone:c.phone,email:c.email,kebele:c.kebele}});});
app.post('/api/citizen/logout',(req,res)=>{res.clearCookie('mesob_citizen');res.json({ok:true})});
app.get('/api/citizen/me',citizenAuth,(req,res)=>{const c=db.prepare('SELECT id,full_name,phone,email,kebele,created_at FROM citizens WHERE id=? AND active=1').get(req.citizen.id);if(!c)return res.status(404).json({error:'Account not found'});res.json(c)});
app.put('/api/citizen/profile',citizenAuth,(req,res)=>{const fullName=String(req.body.full_name||'').trim(),email=String(req.body.email||'').trim(),kebele=String(req.body.kebele||'').trim();if(fullName.length<2)return res.status(400).json({error:'ሙሉ ስም ያስገቡ።'});db.prepare('UPDATE citizens SET full_name=?,email=?,kebele=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(fullName,email,kebele,req.citizen.id);res.json({ok:true})});
app.put('/api/citizen/password',citizenAuth,(req,res)=>{const current=String(req.body.current_password||''),next=String(req.body.new_password||'');const c=db.prepare('SELECT * FROM citizens WHERE id=?').get(req.citizen.id);if(!c||!bcrypt.compareSync(current,c.password_hash))return res.status(401).json({error:'የአሁኑ ይለፍ ቃል ትክክል አይደለም።'});if(next.length<10)return res.status(400).json({error:'አዲሱ ይለፍ ቃል 10+ ቁምፊ ይኑረው።'});db.prepare('UPDATE citizens SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(bcrypt.hashSync(next,12),c.id);res.clearCookie('mesob_citizen');res.json({ok:true})});
app.get('/api/citizen/requests',citizenAuth,(req,res)=>res.json(db.prepare(`SELECT r.id,r.reference_no,r.service_name_am,r.service_name_en,r.status,r.priority,r.due_date,r.admin_note,r.created_at,r.updated_at,i.name_am office_name_am,i.name_en office_name_en FROM service_requests r LEFT JOIN institutions i ON i.id=r.assigned_institution_id WHERE r.citizen_id=? OR (r.citizen_id IS NULL AND r.phone=(SELECT phone FROM citizens WHERE id=?)) ORDER BY r.id DESC`).all(req.citizen.id,req.citizen.id)));
app.get('/api/citizen/requests/:id',citizenAuth,(req,res)=>{const r=db.prepare(`SELECT r.*,i.name_am office_name_am,i.name_en office_name_en FROM service_requests r LEFT JOIN institutions i ON i.id=r.assigned_institution_id WHERE r.id=? AND (r.citizen_id=? OR (r.citizen_id IS NULL AND r.phone=(SELECT phone FROM citizens WHERE id=?)))`).get(req.params.id,req.citizen.id,req.citizen.id);if(!r)return res.status(404).json({error:'Request not found'});r.timeline=db.prepare('SELECT status,note,actor,created_at FROM request_updates WHERE request_id=? ORDER BY id').all(r.id);r.documents=db.prepare('SELECT id,original_name,mime_type,size,created_at FROM service_request_documents WHERE request_id=? ORDER BY id').all(r.id);r.payments=db.prepare('SELECT id,reference_no,provider,amount,currency,status,provider_reference,checkout_url,created_at,updated_at FROM payments WHERE request_id=? ORDER BY id DESC').all(r.id);r.workflow_steps=workflowForRequest(r);r.workflow_logs=db.prepare('SELECT step_key,step_name_am,step_name_en,action,actor,note,created_at FROM service_workflow_logs WHERE request_id=? ORDER BY id').all(r.id);try{r.form_data=JSON.parse(r.form_data||'{}')}catch{r.form_data={}};res.json(r)});
app.get('/api/citizen/notifications',citizenAuth,(req,res)=>res.json(db.prepare('SELECT * FROM notifications WHERE citizen_id=? ORDER BY id DESC LIMIT 100').all(req.citizen.id)));
app.post('/api/citizen/notifications/:id/read',citizenAuth,(req,res)=>{db.prepare("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND citizen_id=?").run(req.params.id,req.citizen.id);res.json({ok:true})});
app.get('/api/admin/staff',auth,requireRole('superadmin','admin'),(req,res)=>res.json(db.prepare('SELECT a.id,a.email,a.full_name,a.role,a.institution_id,a.active,a.last_login_at,a.created_at,i.name_am institution_name_am,i.name_en institution_name_en FROM admins a LEFT JOIN institutions i ON i.id=a.institution_id ORDER BY a.id DESC').all()));
app.post('/api/admin/staff',auth,requireRole('superadmin','admin'),(req,res)=>{const email=String(req.body.email||'').trim(),fullName=String(req.body.full_name||'').trim(),password=String(req.body.password||''),role=String(req.body.role||'viewer'),institutionId=Number(req.body.institution_id)||null;const roles=new Set(['admin','editor','office_staff','viewer']);if(!email||!fullName||password.length<10||!roles.has(role))return res.status(400).json({error:'Email፣ ስም፣ 10+ ቁምፊ የይለፍ ቃል እና ትክክለኛ role ያስገቡ።'});if(role==='office_staff'&&!institutionId)return res.status(400).json({error:'Office staff ለመፍጠር ፅ/ቤት ይምረጡ።'});if(db.prepare('SELECT id FROM admins WHERE email=?').get(email))return res.status(409).json({error:'ይህ email ቀድሞ ተመዝግቧል።'});const r=db.prepare('INSERT INTO admins(email,password_hash,full_name,role,institution_id,active) VALUES(?,?,?,?,?,1)').run(email,bcrypt.hashSync(password,12),fullName,role,institutionId);res.status(201).json({id:r.lastInsertRowid});});
app.put('/api/admin/staff/:id',auth,requireRole('superadmin','admin'),(req,res)=>{const id=Number(req.params.id);const role=String(req.body.role||'viewer'),institutionId=Number(req.body.institution_id)||null,active=req.body.active===0?0:1,fullName=String(req.body.full_name||'').trim();if(!new Set(['admin','editor','office_staff','viewer']).has(role))return res.status(400).json({error:'Invalid role'});if(role==='office_staff'&&!institutionId)return res.status(400).json({error:'Office staff ለመፍጠር ፅ/ቤት ይምረጡ።'});if(id===req.admin.id&&active===0)return res.status(400).json({error:'ራስዎን ማጥፋት አይችሉም።'});db.prepare('UPDATE admins SET full_name=?,role=?,institution_id=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(fullName,role,institutionId,active,id);res.json({ok:true});});
app.put('/api/admin/staff/:id/password',auth,requireRole('superadmin','admin'),(req,res)=>{const next=String(req.body.new_password||'');if(next.length<10)return res.status(400).json({error:'የይለፍ ቃል 10+ ቁምፊ ይኑረው።'});db.prepare('UPDATE admins SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(bcrypt.hashSync(next,12),req.params.id);res.json({ok:true});});
app.put('/api/auth/password',auth,(req,res)=>{const current=String(req.body.current_password||'');const next=String(req.body.new_password||'');if(next.length<10)return res.status(400).json({error:'አዲሱ የይለፍ ቃል ቢያንስ 10 ቁምፊ ይኑረው።'});const a=db.prepare('SELECT * FROM admins WHERE id=?').get(req.admin.id);if(!a||!bcrypt.compareSync(current,a.password_hash))return res.status(401).json({error:'የአሁኑ የይለፍ ቃል ትክክል አይደለም።'});db.prepare('UPDATE admins SET password_hash=? WHERE id=?').run(bcrypt.hashSync(next,12),a.id);res.clearCookie('mesob_admin');res.json({ok:true});});
app.get('/api/admin/backup',auth,requireRole('superadmin','admin'),async(req,res)=>{try{const out=path.resolve('data','mesob-backup.sqlite');await db.backup(out);res.download(out,'enewari-mesob-backup.sqlite',()=>{try{fs.unlinkSync(out)}catch{}})}catch(e){console.error(e);res.status(500).json({error:'Backup failed'})}});
app.get('/api/public/settings',(req,res)=>{const rows=db.prepare('SELECT key,value FROM site_settings').all();res.json(Object.fromEntries(rows.map(x=>[x.key,x.value])));});
app.get('/api/admin/settings',auth,requireRole('superadmin','admin'),(req,res)=>{const rows=db.prepare('SELECT key,value FROM site_settings ORDER BY key').all();res.json(Object.fromEntries(rows.map(x=>[x.key,x.value])));});
app.put('/api/admin/settings',auth,requireRole('superadmin','admin'),(req,res)=>{const allowed=['city_name_am','city_name_en','address','phone','email','facebook','tiktok','map_url','work_hours','about_am','about_en','mission_am','mission_en','vision_am','vision_en','mayor_name_am','mayor_name_en','city_profile_am','city_profile_en','population','area_ha','kebele_count','elevation_m','coordinates','profile_source_name','profile_source_url','footer_text_am','footer_text_en','privacy_url','terms_url','certificate_org_name_am','certificate_org_name_en','certificate_signatory_am','certificate_signatory_en','certificate_title_am','certificate_title_en']; const up=db.prepare('INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP'); const tx=db.transaction(()=>allowed.forEach(k=>up.run(k,String(req.body[k]??''))));tx();res.json({ok:true});});
app.get('/api/public/institutions',(req,res)=>res.json(db.prepare('SELECT * FROM institutions WHERE active=1 ORDER BY id').all()));
app.get('/api/public/institutions/:id',(req,res)=>{const row=db.prepare('SELECT * FROM institutions WHERE id=? AND active=1').get(req.params.id);if(!row)return res.status(404).json({error:'Not found'});res.json(row);});
app.get('/api/public/news',(req,res)=>res.json(db.prepare('SELECT * FROM news WHERE published=1 ORDER BY id DESC LIMIT 20').all()));
app.get('/api/public/documents',(req,res)=>res.json(db.prepare('SELECT * FROM documents ORDER BY id DESC LIMIT 50').all()));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'enewari-digital-mesob',time:new Date().toISOString()}));

function parseService(row){
 let schema=[]; try{schema=JSON.parse(row.form_schema||'[]')}catch{}
 let workflow=[]; try{workflow=JSON.parse(row.workflow_schema||'[]')}catch{}
 return {key:row.service_key,am:row.name_am,en:row.name_en,description_am:row.description_am,description_en:row.description_en,officeId:row.institution_id,fee:Number(row.fee||0),currency:row.currency||'ETB',estimated_days:Number(row.estimated_days||3),required_documents:(row.required_documents||'').split(',').map(x=>x.trim()).filter(Boolean),form_schema:schema,workflow_schema:workflow,payment_required:Number(row.fee||0)>0};
}
function getService(key){const row=db.prepare('SELECT * FROM office_services WHERE service_key=? AND active=1').get(key);return row?parseService(row):null;}

function safeWorkflow(input){try{const a=Array.isArray(input)?input:JSON.parse(input||'[]');const seen=new Set();return a.slice(0,20).map((x,i)=>{const key=String(x.key||`step-${i+1}`).toLowerCase().replace(/[^a-z0-9_-]/g,'-').slice(0,40);return {key,name_am:String(x.name_am||'').slice(0,120),name_en:String(x.name_en||'').slice(0,120),status:['Received','In Review','In Progress','Completed','Rejected'].includes(x.status)?x.status:'In Progress',role:String(x.role||'').slice(0,80),terminal:!!x.terminal,order:i+1}}).filter(x=>x.key&&x.name_am&&x.name_en&&!seen.has(x.key)&&seen.add(x.key))}catch{return []}}
function workflowForRequest(r){let a=[];try{a=JSON.parse(r.workflow_schema_snapshot||'[]')}catch{}return a}
function safeSchema(input){try{const a=Array.isArray(input)?input:JSON.parse(input||'[]');return a.slice(0,20).map(x=>({name:String(x.name||'').replace(/[^a-zA-Z0-9_]/g,'').slice(0,40),label_am:String(x.label_am||'').slice(0,120),label_en:String(x.label_en||'').slice(0,120),type:['text','number','date','email','tel','textarea','select'].includes(x.type)?x.type:'text',required:!!x.required,options:Array.isArray(x.options)?x.options.slice(0,20).map(v=>String(v).slice(0,100)):[]})).filter(x=>x.name&&x.label_am&&x.label_en)}catch{return []}}
const requestLimiter=rateLimit({windowMs:10*60*1000,max:12,standardHeaders:true,legacyHeaders:false,message:{error:'በጣም ብዙ ጥያቄዎች ተልከዋል። እባክዎ ቆይተው ይሞክሩ።'}});
function makeRef(){return 'ENW-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+Math.random().toString(36).slice(2,7).toUpperCase();}
app.get('/api/public/certificates/verify',(req,res)=>{const code=String(req.query.code||'').trim().toUpperCase();if(!code)return res.status(400).json({error:'Verification code is required'});const c=db.prepare('SELECT certificate_no,verification_code,title_am,title_en,holder_name,service_name_am,service_name_en,issued_by,issued_at,expires_at,status,notes FROM certificates WHERE verification_code=?').get(code);if(!c)return res.status(404).json({valid:false,error:'የማረጋገጫ ኮዱ አልተገኘም።'});const expired=c.expires_at && new Date(c.expires_at)<new Date();res.json({valid:c.status==='Valid'&&!expired,expired,...c});});
app.get('/api/public/certificates/qr',(req,res)=>{const code=String(req.query.code||'').trim().toUpperCase();if(!code)return res.status(400).send('Missing code');res.setHeader('Cache-Control','public,max-age=3600');QRCode.toDataURL(`${req.protocol}://${req.get('host')}/verify.html?code=${encodeURIComponent(code)}`,{width:420,margin:2,errorCorrectionLevel:'M'}).then(data=>res.json({data,verify_url:`${req.protocol}://${req.get('host')}/verify.html?code=${encodeURIComponent(code)}`})).catch(()=>res.status(500).json({error:'QR generation failed'}));});
app.get('/api/admin/certificates',auth,requireRole('superadmin','admin','viewer','editor'),(req,res)=>{const rows=db.prepare('SELECT c.*,r.reference_no request_reference FROM certificates c LEFT JOIN service_requests r ON r.id=c.request_id ORDER BY c.id DESC LIMIT 500').all();res.json(rows);});
app.post('/api/admin/certificates',auth,requireRole('superadmin','admin','editor'),(req,res)=>{const requestId=Number(req.body.request_id||0)||null;const r=requestId?db.prepare('SELECT * FROM service_requests WHERE id=?').get(requestId):null;if(requestId&&!r)return res.status(404).json({error:'Request not found'});const holder=String(req.body.holder_name||r?.full_name||'').trim();const titleAm=String(req.body.title_am||'የማረጋገጫ ሰነድ').trim();const titleEn=String(req.body.title_en||'Official Certificate').trim();if(holder.length<2)return res.status(400).json({error:'Holder name is required'});const certNo='ECA-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-7);const code=randomUUID().replaceAll('-','').slice(0,20).toUpperCase();const serviceAm=String(req.body.service_name_am||r?.service_name_am||'').trim();const serviceEn=String(req.body.service_name_en||r?.service_name_en||'').trim();const issuedBy=String(req.body.issued_by||'Enewari City Administration').trim();const expiresAt=String(req.body.expires_at||'').trim();const notes=String(req.body.notes||'').slice(0,1000);const result=db.prepare('INSERT INTO certificates(certificate_no,verification_code,request_id,citizen_id,title_am,title_en,holder_name,service_name_am,service_name_en,issued_by,expires_at,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(certNo,code,requestId,r?.citizen_id||null,titleAm,titleEn,holder,serviceAm,serviceEn,issuedBy,expiresAt,'Valid',notes);res.status(201).json({id:result.lastInsertRowid,certificate_no:certNo,verification_code:code,verify_url:'/verify.html?code='+code});});
app.put('/api/admin/certificates/:id',auth,requireRole('superadmin','admin','editor'),(req,res)=>{const status=['Valid','Revoked','Expired'].includes(req.body.status)?req.body.status:'Valid';db.prepare('UPDATE certificates SET status=?,notes=?,expires_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,String(req.body.notes||'').slice(0,1000),String(req.body.expires_at||''),req.params.id);res.json({ok:true});});

app.get('/api/public/services',(req,res)=>res.json(db.prepare('SELECT * FROM office_services WHERE active=1 ORDER BY institution_id,id').all().map(parseService)));
app.get('/api/public/services/:key',(req,res)=>{const svc=getService(req.params.key);if(!svc)return res.status(404).json({error:'Service not found'});res.json(svc)});
app.get('/api/admin/services',auth,requireRole('superadmin','admin','editor','office_staff','viewer'),(req,res)=>{let q='SELECT s.*,i.name_am institution_name_am,i.name_en institution_name_en FROM office_services s LEFT JOIN institutions i ON i.id=s.institution_id';const a=[];if(req.admin.role==='office_staff'&&req.admin.institution_id){q+=' WHERE s.institution_id=?';a.push(req.admin.institution_id)}q+=' ORDER BY s.institution_id,s.id';res.json(db.prepare(q).all(...a));});
app.post('/api/admin/services',auth,requireRole('superadmin','admin','editor'),(req,res)=>{const key=String(req.body.service_key||'').trim().toLowerCase().replace(/[^a-z0-9_-]/g,'-');const institutionId=Number(req.body.institution_id);if(!key||!institutionId||!String(req.body.name_am||'').trim()||!String(req.body.name_en||'').trim())return res.status(400).json({error:'የአገልግሎት መለያ፣ ስም እና ፅ/ቤት ያስፈልጋል።'});try{const r=db.prepare('INSERT INTO office_services(institution_id,service_key,name_am,name_en,description_am,description_en,fee,currency,estimated_days,required_documents,form_schema,workflow_schema,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(institutionId,key,String(req.body.name_am).trim(),String(req.body.name_en).trim(),String(req.body.description_am||''),String(req.body.description_en||''),Math.max(0,Number(req.body.fee||0)),String(req.body.currency||'ETB').slice(0,8),Math.max(0,Number(req.body.estimated_days||3)),String(req.body.required_documents||'').slice(0,1000),JSON.stringify(safeSchema(req.body.form_schema)),JSON.stringify(safeWorkflow(req.body.workflow_schema)),req.body.active===0?0:1);res.status(201).json({id:r.lastInsertRowid});}catch(e){res.status(409).json({error:'ይህ service key አስቀድሞ አለ።'});}});
app.put('/api/admin/services/:id',auth,requireRole('superadmin','admin','editor'),(req,res)=>{const old=db.prepare('SELECT * FROM office_services WHERE id=?').get(req.params.id);if(!old)return res.status(404).json({error:'Not found'});const institutionId=Number(req.body.institution_id||old.institution_id);if(req.admin.role==='office_staff'&&institutionId!==req.admin.institution_id)return res.status(403).json({error:'Forbidden'});const key=String(req.body.service_key||old.service_key).trim().toLowerCase().replace(/[^a-z0-9_-]/g,'-');db.prepare('UPDATE office_services SET institution_id=?,service_key=?,name_am=?,name_en=?,description_am=?,description_en=?,fee=?,currency=?,estimated_days=?,required_documents=?,form_schema=?,workflow_schema=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(institutionId,key,String(req.body.name_am||''),String(req.body.name_en||''),String(req.body.description_am||''),String(req.body.description_en||''),Math.max(0,Number(req.body.fee||0)),String(req.body.currency||'ETB').slice(0,8),Math.max(0,Number(req.body.estimated_days||3)),String(req.body.required_documents||'').slice(0,1000),JSON.stringify(safeSchema(req.body.form_schema)),JSON.stringify(safeWorkflow(req.body.workflow_schema)),req.body.active===0?0:1,req.params.id);res.json({ok:true});});
app.delete('/api/admin/services/:id',auth,requireRole('superadmin','admin'),(req,res)=>{db.prepare('UPDATE office_services SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(req.params.id);res.json({ok:true});});
app.get('/api/admin/service-requests/:id/workflow',auth,scopeRequests,(req,res)=>{const r=db.prepare('SELECT * FROM service_requests WHERE id=?').get(req.params.id);if(!r)return res.status(404).json({error:'Request not found'});if(req.officeScope&&r.assigned_institution_id!==req.officeScope)return res.status(403).json({error:'Forbidden'});const steps=workflowForRequest(r);const logs=db.prepare('SELECT * FROM service_workflow_logs WHERE request_id=? ORDER BY id').all(r.id);res.json({current_step_key:r.current_step_key||steps[0]?.key||'',steps,logs});});
app.put('/api/admin/service-requests/:id/workflow',auth,scopeRequests,(req,res)=>{const r=db.prepare('SELECT * FROM service_requests WHERE id=?').get(req.params.id);if(!r)return res.status(404).json({error:'Request not found'});if(req.officeScope&&r.assigned_institution_id!==req.officeScope)return res.status(403).json({error:'Forbidden'});const steps=workflowForRequest(r);const target=steps.find(x=>x.key===String(req.body.step_key||''));if(!target)return res.status(400).json({error:'የሂደት ደረጃ አልተገኘም።'});const note=String(req.body.note||'').slice(0,1000);db.prepare('UPDATE service_requests SET current_step_key=?,status=?,admin_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(target.key,target.status,note,r.id);db.prepare('INSERT INTO service_workflow_logs(request_id,step_key,step_name_am,step_name_en,action,actor,note) VALUES(?,?,?,?,?,?,?)').run(r.id,target.key,target.name_am,target.name_en,'transition',req.admin.email,note);db.prepare('INSERT INTO request_updates(request_id,status,note,actor) VALUES(?,?,?,?)').run(r.id,target.status,note,req.admin.email);if(r.status!==target.status&&r.citizen_id){db.prepare('INSERT INTO notifications(request_id,citizen_id,channel,recipient,message) VALUES(?,?,?,?,?)').run(r.id,r.citizen_id,'in-app',r.phone,`የጥያቄ ${r.reference_no} ሂደት: ${target.name_am} — ${target.status}`);}res.json({ok:true,current_step_key:target.key,status:target.status});});
app.post('/api/public/service-requests',requestLimiter,requestUpload.array('documents',5),async(req,res)=>{
 const serviceKey=String(req.body.service_key||'general'); const svc=getService(serviceKey);
 const fullName=String(req.body.full_name||'').trim(), phone=String(req.body.phone||'').trim(), details=String(req.body.details||'').trim();
 if(!svc||fullName.length<2||phone.length<7||details.length<5){for(const f of req.files||[])try{fs.unlinkSync(f.path)}catch{};return res.status(400).json({error:'እባክዎ የአገልግሎት፣ ሙሉ ስም፣ ስልክ እና ዝርዝር ጥያቄ በትክክል ይሙሉ።'});}
 if(svc.required_documents.length && !(req.files||[]).length){return res.status(400).json({error:`ለዚህ አገልግሎት የሚፈለጉ ሰነዶች፦ ${svc.required_documents.join(', ')}። ቢያንስ አንድ ሰነድ ያያይዙ።`});}
 const formData={}; for(const f of svc.form_schema){const v=String(req.body[f.name]||'').trim();if(f.required&&!v){for(const x of req.files||[])try{fs.unlinkSync(x.path)}catch{};return res.status(400).json({error:`${f.label_am} ያስፈልጋል።`});}if(v)formData[f.name]=v;}
 let ref; for(let i=0;i<5;i++){const candidate=makeRef(); if(!db.prepare('SELECT 1 FROM service_requests WHERE reference_no=?').get(candidate)){ref=candidate;break;}}
 if(!ref){for(const f of req.files||[])try{fs.unlinkSync(f.path)}catch{};return res.status(500).json({error:'Reference generation failed'});}
 const kebele=String(req.body.kebele||'').trim(); const citizenId=req.cookies.mesob_citizen ? (()=>{try{return jwt.verify(req.cookies.mesob_citizen,JWT_SECRET).id}catch{return null}})() : null;
 const due=new Date(Date.now()+svc.estimated_days*86400000).toISOString().slice(0,10);
 const tx=db.transaction(()=>{db.prepare('INSERT INTO service_requests(reference_no,service_key,service_name_am,service_name_en,full_name,phone,kebele,details,form_data,assigned_institution_id,citizen_id,due_date,current_step_key,workflow_schema_snapshot) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(ref,serviceKey,svc.am,svc.en,fullName,phone,kebele,details,JSON.stringify(formData),svc.officeId,citizenId,due,svc.workflow_schema?.[0]?.key||'',JSON.stringify(svc.workflow_schema||[]));const requestId=db.prepare('SELECT id FROM service_requests WHERE reference_no=?').get(ref).id;for(const f of req.files||[])db.prepare('INSERT INTO service_request_documents(request_id,filename,original_name,mime_type,size) VALUES(?,?,?,?,?)').run(requestId,f.filename,f.originalname,f.mimetype,f.size);db.prepare('INSERT INTO request_updates(request_id,status,note,actor) VALUES(?,?,?,?)').run(requestId,'Received','ጥያቄው በድረ-ገጽ ተቀብሏል።','system');if(svc.fee>0)db.prepare('INSERT INTO payments(request_id,reference_no,provider,amount,currency,status) VALUES(?,?,?,?,?,?)').run(requestId,ref,process.env.PAYMENT_PROVIDER||'manual',svc.fee,svc.currency||process.env.PAYMENT_CURRENCY||'ETB','Pending');});
 try{tx()}catch(e){for(const f of req.files||[])try{fs.unlinkSync(f.path)}catch{};return res.status(500).json({error:'ጥያቄው ማስቀመጥ አልተቻለም።'});}
 const requestId=db.prepare('SELECT id FROM service_requests WHERE reference_no=?').get(ref).id; if(citizenId)queueCitizenNotifications(requestId,citizenId,phone,`የጥያቄ ${ref} ተቀብሏል።`);res.status(201).json({ok:true,reference_no:ref,message:`የ${svc.am} ጥያቄዎ ተቀብሏል። ማጣቀሻ ቁጥርዎ ${ref} ነው።`,payment_required:svc.payment_required,fee:svc.fee,currency:svc.currency,due_date:due});
});
app.get('/api/public/service-requests/status',(req,res)=>{const ref=String(req.query.reference_no||'').trim(),phone=String(req.query.phone||'').trim();if(!ref||!phone)return res.status(400).json({error:'Reference number and phone are required'});const r=db.prepare('SELECT r.reference_no,r.service_name_am,r.service_name_en,r.status,r.admin_note,r.priority,r.due_date,r.created_at,r.updated_at,i.name_am office_name_am,i.name_en office_name_en FROM service_requests r LEFT JOIN institutions i ON i.id=r.assigned_institution_id WHERE r.reference_no=? AND r.phone=?').get(ref,phone);if(!r)return res.status(404).json({error:'የጥያቄው መረጃ አልተገኘም።'});r.timeline=db.prepare('SELECT status,note,actor,created_at FROM request_updates WHERE request_id=(SELECT id FROM service_requests WHERE reference_no=? AND phone=?) ORDER BY id').all(ref,phone);res.json(r);});
app.get('/api/admin/service-requests',auth,scopeRequests,(req,res)=>{const status=String(req.query.status||'').trim();const office=Number(req.query.office||0);let q='SELECT r.*,i.name_am office_name_am,i.name_en office_name_en FROM service_requests r LEFT JOIN institutions i ON i.id=r.assigned_institution_id';const w=[],p=[];if(status){w.push('r.status=?');p.push(status)}if(office){w.push('r.assigned_institution_id=?');p.push(office)} if(req.officeScope){w.push('r.assigned_institution_id=?');p.push(req.officeScope)}if(w.length)q+=' WHERE '+w.join(' AND ');q+=' ORDER BY r.id DESC LIMIT 300';res.json(db.prepare(q).all(...p));});
app.get('/api/admin/service-requests/:id/history',auth,scopeRequests,(req,res)=>res.json(db.prepare('SELECT * FROM request_updates WHERE request_id=? ORDER BY id').all(req.params.id)));
app.put('/api/admin/service-requests/:id',auth,scopeRequests,(req,res)=>{const allowed=new Set(['Received','In Review','In Progress','Completed','Rejected']);const status=String(req.body.status||'Received');if(!allowed.has(status))return res.status(400).json({error:'Invalid status'});const note=String(req.body.admin_note||'');const office=req.officeScope||Number(req.body.assigned_institution_id)||null;const priority=['Low','Normal','High','Urgent'].includes(String(req.body.priority))?String(req.body.priority):'Normal';const due=String(req.body.due_date||'');const old=db.prepare('SELECT * FROM service_requests WHERE id=?').get(req.params.id);if(!old)return res.status(404).json({error:'Not found'});if(req.officeScope && old.assigned_institution_id!==req.officeScope)return res.status(403).json({error:'ይህ ጥያቄ ለእርስዎ የተመደበ አይደለም።'});db.prepare('UPDATE service_requests SET status=?,admin_note=?,assigned_institution_id=?,priority=?,due_date=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,note,office,priority,due,req.params.id);if(old.status!==status||old.admin_note!==note||old.assigned_institution_id!==office)db.prepare('INSERT INTO request_updates(request_id,status,note,actor) VALUES(?,?,?,?)').run(req.params.id,status,note,req.admin.email);if(old.status!==status){const msg=`የጥያቄ ${old.reference_no} ሁኔታ: ${status}`;db.prepare('INSERT INTO notifications(request_id,citizen_id,channel,recipient,message) VALUES(?,?,?,?,?)').run(req.params.id,old.citizen_id,'in-app',old.phone,msg);}res.json({ok:true});});
app.get('/api/public/service-requests/:id/documents',citizenAuth,(req,res)=>{const r=db.prepare('SELECT id FROM service_requests WHERE id=? AND (citizen_id=? OR (citizen_id IS NULL AND phone=(SELECT phone FROM citizens WHERE id=?)))').get(req.params.id,req.citizen.id,req.citizen.id);if(!r)return res.status(404).json({error:'Request not found'});res.json(db.prepare('SELECT id,original_name,mime_type,size,created_at FROM service_request_documents WHERE request_id=? ORDER BY id').all(r.id));});
app.get('/api/public/payments/:requestId',citizenAuth,(req,res)=>{const r=db.prepare('SELECT id FROM service_requests WHERE id=? AND (citizen_id=? OR (citizen_id IS NULL AND phone=(SELECT phone FROM citizens WHERE id=?)))').get(req.params.requestId,req.citizen.id,req.citizen.id);if(!r)return res.status(404).json({error:'Request not found'});res.json(db.prepare('SELECT id,reference_no,provider,amount,currency,status,provider_reference,checkout_url,created_at,updated_at FROM payments WHERE request_id=? ORDER BY id DESC').all(r.id));});
app.post('/api/public/payments/:id/initiate',citizenAuth,async(req,res)=>{const p=db.prepare('SELECT p.*,r.citizen_id,r.phone FROM payments p JOIN service_requests r ON r.id=p.request_id WHERE p.id=?').get(req.params.id);if(!p||p.citizen_id!==req.citizen.id)return res.status(404).json({error:'Payment not found'});if(p.amount<=0)return res.status(400).json({error:'No payment is required'});if(p.status==='Verified')return res.json(p);const provider=(process.env.PAYMENT_PROVIDER||'manual').toLowerCase();if(provider==='chapa'&&process.env.CHAPA_SECRET_KEY){try{const r=await fetch('https://api.chapa.co/v1/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${process.env.CHAPA_SECRET_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({amount:String(p.amount),currency:p.currency,email:(db.prepare('SELECT email FROM citizens WHERE id=?').get(req.citizen.id)?.email||'enewari@example.com'),first_name:(db.prepare('SELECT full_name FROM citizens WHERE id=?').get(req.citizen.id)?.full_name||'Citizen').split(' ')[0],tx_ref:p.reference_no,callback_url:process.env.PAYMENT_CALLBACK_URL||'',return_url:process.env.PAYMENT_RETURN_URL||''})});const j=await r.json();if(r.ok&&j.status==='success'){db.prepare("UPDATE payments SET status='Initiated',checkout_url=?,provider_reference=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(j.data?.checkout_url||'',j.data?.tx_ref||p.reference_no,p.id);return res.json(db.prepare('SELECT * FROM payments WHERE id=?').get(p.id));}}catch(e){console.error('payment provider error',e.message)}}res.json({id:p.id,reference_no:p.reference_no,amount:p.amount,currency:p.currency,status:'Pending',message:'የክፍያ አቅራቢ አልተዋቀረም። Admin እስኪያዋቅር ድረስ ክፍያ አይተገበርም።'});});
app.post('/api/payments/webhook',async(req,res)=>{const secret=process.env.PAYMENT_WEBHOOK_SECRET;if(!secret||req.get('x-payment-secret')!==secret)return res.status(401).json({error:'Unauthorized'});const ref=String(req.body.tx_ref||req.body.reference_no||'').trim(),status=String(req.body.status||'').toLowerCase();if(!ref)return res.status(400).json({error:'Reference required'});const p=db.prepare('SELECT * FROM payments WHERE reference_no=?').get(ref);if(!p)return res.status(404).json({error:'Payment not found'});const next=status==='success'||status==='paid'||status==='completed'?'Verified':status==='failed'?'Failed':p.status;db.prepare('UPDATE payments SET status=?,provider_reference=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(next,String(req.body.provider_reference||req.body.transaction_id||''),p.id);res.json({ok:true,status:next});});
app.get('/api/admin/service-requests/:id/documents',auth,scopeRequests,(req,res)=>{const r=db.prepare('SELECT assigned_institution_id FROM service_requests WHERE id=?').get(req.params.id);if(!r)return res.status(404).json({error:'Request not found'});if(req.officeScope&&r.assigned_institution_id!==req.officeScope)return res.status(403).json({error:'Forbidden'});res.json(db.prepare('SELECT * FROM service_request_documents WHERE request_id=? ORDER BY id').all(req.params.id));});
app.get('/api/admin/payments',auth,requireRole('superadmin','admin','viewer','editor','office_staff'),(req,res)=>{const scope=req.admin.role==='office_staff'&&req.admin.institution_id;let q='SELECT p.*,r.service_name_am,r.phone,i.name_am office_name_am FROM payments p JOIN service_requests r ON r.id=p.request_id LEFT JOIN institutions i ON i.id=r.assigned_institution_id';const args=[];if(scope){q+=' WHERE r.assigned_institution_id=?';args.push(req.admin.institution_id)}q+=' ORDER BY p.id DESC LIMIT 300';res.json(db.prepare(q).all(...args));});
app.get('/api/admin/operations',auth,(req,res)=>{const status=String(req.query.status||'').trim();const priority=String(req.query.priority||'').trim();const office=Number(req.query.office||0);const q=String(req.query.q||'').trim();const where=['1=1'];const args=[];if(status){where.push('r.status=?');args.push(status)}if(priority){where.push('r.priority=?');args.push(priority)}if(office){where.push('r.assigned_institution_id=?');args.push(office)}if(req.admin.role==='office_staff'&&req.admin.institution_id){where.push('r.assigned_institution_id=?');args.push(req.admin.institution_id)}if(q){where.push('(r.reference_no LIKE ? OR r.full_name LIKE ? OR r.phone LIKE ? OR r.service_name_am LIKE ?)');const x='%'+q+'%';args.push(x,x,x,x)}const rows=db.prepare(`SELECT r.*,i.name_am office_name_am,i.name_en office_name_en,CASE WHEN r.due_date!='' AND r.status NOT IN ('Completed','Rejected') AND datetime(r.due_date)<datetime('now') THEN 1 ELSE 0 END overdue FROM service_requests r LEFT JOIN institutions i ON i.id=r.assigned_institution_id WHERE ${where.join(' AND ')} ORDER BY overdue DESC, CASE r.priority WHEN 'Urgent' THEN 1 WHEN 'High' THEN 2 WHEN 'Normal' THEN 3 ELSE 4 END, r.id DESC LIMIT 500`).all(...args);const summary={total:rows.length,overdue:rows.filter(x=>x.overdue).length,urgent:rows.filter(x=>x.priority==='Urgent'&&x.status!=='Completed'&&x.status!=='Rejected').length,inProgress:rows.filter(x=>['In Review','In Progress'].includes(x.status)).length};res.json({summary,rows});});
app.post('/api/admin/operations/bulk-assign',auth,requireRole('superadmin','admin'),(req,res)=>{const ids=Array.isArray(req.body.request_ids)?req.body.request_ids.map(Number).filter(Boolean):[];const office=Number(req.body.institution_id||0);if(!ids.length||!office)return res.status(400).json({error:'Requests and institution are required'});const tx=db.transaction(()=>{for(const id of ids){const old=db.prepare('SELECT * FROM service_requests WHERE id=?').get(id);if(!old)continue;db.prepare('UPDATE service_requests SET assigned_institution_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(office,id);if(old.assigned_institution_id!==office){db.prepare('INSERT INTO request_updates(request_id,status,note,actor) VALUES(?,?,?,?)').run(id,old.status,'የስራ ምደባ ተቀይሯል።',req.admin.email);}}});tx();res.json({ok:true,count:ids.length});});
app.get('/api/admin/stats',auth,(req,res)=>{const total=db.prepare('SELECT COUNT(*) c FROM service_requests').get().c;const received=db.prepare("SELECT COUNT(*) c FROM service_requests WHERE status='Received'").get().c;const progress=db.prepare("SELECT COUNT(*) c FROM service_requests WHERE status IN ('In Review','In Progress')").get().c;const completed=db.prepare("SELECT COUNT(*) c FROM service_requests WHERE status='Completed'").get().c;const rejected=db.prepare("SELECT COUNT(*) c FROM service_requests WHERE status='Rejected'").get().c;const offices=db.prepare('SELECT i.id,i.name_am,COUNT(r.id) count FROM institutions i LEFT JOIN service_requests r ON r.assigned_institution_id=i.id GROUP BY i.id ORDER BY count DESC,i.id').all();res.json({total,received,progress,completed,rejected,offices});});
crud('institutions',['name_am','name_en','description_am','description_en','phone','email','address','head_am','head_en','work_hours','services_am','services_en','forms_url','photo_url','icon','active'],['admin']);
crud('news',['title_am','title_en','body_am','body_en','image','published'],['admin','editor']);
app.post('/api/admin/documents',auth,requireRole('superadmin','admin','editor'),upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'File required'}); const r=db.prepare('INSERT INTO documents(title_am,title_en,category,filename,original_name,mime_type,size) VALUES(?,?,?,?,?,?,?)').run(req.body.title_am||req.file.originalname,req.body.title_en||'',req.body.category||'General',req.file.filename,req.file.originalname,req.file.mimetype,req.file.size);res.json({id:r.lastInsertRowid});});
app.delete('/api/admin/documents/:id',auth,requireRole('superadmin','admin','editor'),(req,res)=>{const d=db.prepare('SELECT * FROM documents WHERE id=?').get(req.params.id);if(d){try{fs.unlinkSync(path.join(uploadDir,d.filename))}catch{} db.prepare('DELETE FROM documents WHERE id=?').run(req.params.id)}res.json({ok:true})});

function localAnswer(q){const x=q.toLowerCase(); if(x.includes('ተቋም')||x.includes('institution')){return 'የእነዋሪ ከተማ አስተዳደር 12 ዋና ተቋማት አሉት። ከንቲባ ፅ/ቤት፣ ከተማና መሰረተልማት፣ መሬት፣ ኢንቨስትመንት፣ ገንዘብ፣ ሴቶች/ህፃናት/ወጣቶች፣ ስፖርት/ባህል/ቱሪዝም፣ ገቢዎች፣ ስራና ክህሎት፣ ንግድ፣ ምክር ቤት እና ፖሊስ ፅ/ቤት።'} if(x.includes('ግብር')||x.includes('tax')) return 'የግብርና ገቢ ጉዳዮች ከገቢዎች ፅ/ቤት ጋር ይያያዛሉ። የግል ግብር መጠን ወይም ዕዳ ለማየት የቀጥታ የገቢ ዳታቤዝ/API ግንኙነት ያስፈልጋል።'; if(x.includes('ውሃ')||x.includes('water')) return 'የእነዋሪ ከተማ የውሃ አገልግሎት ስርዓት የቀጥታ ዳታ እስካሁን አልተገናኘም። የአገልግሎት መመሪያ ካለ ከአስተዳደሩ ማረጋገጥ ያስፈልጋል።'; if(x.includes('ቅጣት')||x.includes('traffic')) return 'የትራፊክ ቅጣት መረጃ ከፖሊስ ፅ/ቤት ወይም ተዛማጅ የትራፊክ ስርዓት ጋር API ሲገናኝ በቀጥታ ይመጣል።'; return 'ጥያቄዎን ተቀብያለሁ። ይህ ስርዓት ከአስተዳደሩ ዳታቤዝ ጋር ሲገናኝ የተቋማት፣ ዜና፣ ሰነዶችና አገልግሎቶችን በቀጥታ ማፈላለግ ይችላል።';}
async function aiAnswer(message){
 const provider=(process.env.AI_PROVIDER||'local').toLowerCase();
 const context=db.prepare('SELECT name_am,name_en,description_am,description_en FROM institutions WHERE active=1').all().map(x=>`${x.name_am} / ${x.name_en}: ${x.description_am}`).join('\n');
 const system=`You are Digital Mesob AI for Enewari City Administration. Answer in Amharic unless the user asks English. Only state facts supported by the supplied city data; if not known, say so. Be concise and helpful. City institutions:\n${context}`;
 try{
  if(provider==='openai' && process.env.OPENAI_API_KEY){const {default:OpenAI}=await import('openai'); const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY}); const r=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-6-luna',instructions:system,input:message}); return {text:r.output_text,provider:'openai'};}
  if(provider==='ollama'){const r=await fetch((process.env.OLLAMA_BASE_URL||'http://127.0.0.1:11434')+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OLLAMA_MODEL||'gemma3:4b',stream:false,messages:[{role:'system',content:system},{role:'user',content:message}]})}); if(r.ok){const j=await r.json();return {text:j.message?.content||localAnswer(message),provider:'ollama'}}}
 }catch(e){console.error('AI error',e.message)}
 return {text:localAnswer(message),provider:'local'};
}
app.get('/api/public/service-requests/feedback', (req,res)=>{const reference_no=String(req.query.reference_no||'').trim();const phone=String(req.query.phone||'').trim();if(!reference_no||!phone)return res.status(400).json({error:'Reference Number እና ስልክ ያስፈልጋሉ።'});const r=db.prepare('SELECT id,reference_no,status,full_name,citizen_id FROM service_requests WHERE reference_no=? AND phone=?').get(reference_no,phone);if(!r)return res.status(404).json({error:'የጥያቄው መረጃ አልተገኘም።'});if(r.status!=='Completed')return res.status(400).json({error:'አስተያየት መስጠት የሚችሉት ጥያቄው ከተጠናቀቀ በኋላ ነው።'});const f=db.prepare('SELECT rating,comment,created_at FROM service_feedback WHERE request_id=?').get(r.id);res.json({eligible:true,reference_no:r.reference_no,feedback:f||null});});
app.post('/api/public/service-requests/feedback', (req,res)=>{const reference_no=String(req.body.reference_no||'').trim();const phone=String(req.body.phone||'').trim();const rating=Number(req.body.rating);const comment=String(req.body.comment||'').trim().slice(0,1000);if(!reference_no||!phone||![1,2,3,4,5].includes(rating))return res.status(400).json({error:'Reference, ስልክ እና 1–5 ደረጃ ያስፈልጋሉ።'});const r=db.prepare('SELECT id,reference_no,status,citizen_id FROM service_requests WHERE reference_no=? AND phone=?').get(reference_no,phone);if(!r)return res.status(404).json({error:'የጥያቄው መረጃ አልተገኘም።'});if(r.status!=='Completed')return res.status(400).json({error:'ጥያቄው ገና አልተጠናቀቀም።'});const old=db.prepare('SELECT id FROM service_feedback WHERE request_id=?').get(r.id);if(old){db.prepare('UPDATE service_feedback SET rating=?,comment=?,updated_at=CURRENT_TIMESTAMP WHERE request_id=?').run(rating,comment,r.id);}else{db.prepare('INSERT INTO service_feedback(request_id,citizen_id,reference_no,rating,comment) VALUES(?,?,?,?,?)').run(r.id,r.citizen_id||null,r.reference_no,rating,comment);}res.json({ok:true,message:'አስተያየትዎ ተቀብሏል። እናመሰግናለን!'});});

app.get('/api/admin/notification-status',auth,requireRole('superadmin','admin'),(req,res)=>res.json({config:notificationConfig(),queued:db.prepare("SELECT COUNT(*) c FROM notifications WHERE status='Queued' AND channel!='in-app'").get().c,failed:db.prepare("SELECT COUNT(*) c FROM notifications WHERE status='Failed'").get().c,sent:db.prepare("SELECT COUNT(*) c FROM notifications WHERE status='Sent'").get().c}));
app.get('/api/admin/reports',auth,requireRole('superadmin','admin','viewer','editor','office_staff'),(req,res)=>{const scope=req.admin.role==='office_staff'&&req.admin.institution_id?req.admin.institution_id:null;const where=scope?' WHERE assigned_institution_id=?':'';const args=scope?[scope]:[];const total=db.prepare(`SELECT COUNT(*) c FROM service_requests${where}`).get(...args).c;const byStatus=db.prepare(`SELECT status,COUNT(*) c FROM service_requests${where} GROUP BY status ORDER BY c DESC`).all(...args);const byPriority=db.prepare(`SELECT priority,COUNT(*) c FROM service_requests${where} GROUP BY priority ORDER BY c DESC`).all(...args);const byOffice=db.prepare('SELECT i.name_am,COUNT(r.id) c FROM institutions i LEFT JOIN service_requests r ON r.assigned_institution_id=i.id GROUP BY i.id ORDER BY c DESC').all();const monthly=db.prepare(`SELECT substr(created_at,1,7) month,COUNT(*) c FROM service_requests${where} GROUP BY month ORDER BY month DESC LIMIT 12`).all(...args);const avg=db.prepare(`SELECT ROUND(AVG((julianday(updated_at)-julianday(created_at))*24),1) hours FROM service_requests WHERE status='Completed'${scope?' AND assigned_institution_id=?':''}`).get(...args).hours;res.json({total,byStatus,byPriority,byOffice,monthly,avgCompletionHours:avg});});
app.get('/api/admin/reports/export.csv',auth,requireRole('superadmin','admin','viewer','editor','office_staff'),(req,res)=>{const scope=req.admin.role==='office_staff'&&req.admin.institution_id?req.admin.institution_id:null;const where=scope?' WHERE r.assigned_institution_id=?':'';const args=scope?[scope]:[];const rows=db.prepare(`SELECT r.reference_no AS reference,r.status,r.priority,r.created_at,r.updated_at,i.name_am AS institution FROM service_requests r LEFT JOIN institutions i ON i.id=r.assigned_institution_id${where} ORDER BY r.created_at DESC`).all(...args);const escCsv=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=['Reference,Status,Priority,Created At,Updated At,Institution',...rows.map(x=>[x.reference,x.status,x.priority,x.created_at,x.updated_at,x.institution].map(escCsv).join(','))].join('\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="enewari-service-report.csv"');res.send('\ufeff'+csv);});

app.get('/api/admin/feedback',auth,requireRole('superadmin','admin','viewer','editor'),(req,res)=>{const rows=db.prepare('SELECT f.*,r.service_name_am,r.full_name,i.name_am institution_name_am FROM service_feedback f JOIN service_requests r ON r.id=f.request_id LEFT JOIN institutions i ON i.id=r.assigned_institution_id ORDER BY f.id DESC LIMIT 500').all();const summary=db.prepare('SELECT COUNT(*) total,ROUND(AVG(rating),2) average,SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END) five_star,SUM(CASE WHEN rating<=2 THEN 1 ELSE 0 END) low_rating FROM service_feedback').get();res.json({rows,summary});});

app.get('/api/admin/notifications',auth,requireRole('superadmin','admin'),(req,res)=>res.json(db.prepare('SELECT n.*,c.full_name FROM notifications n LEFT JOIN citizens c ON c.id=n.citizen_id ORDER BY n.id DESC LIMIT 200').all()));
app.post('/api/admin/notifications/:id/retry',auth,requireRole('superadmin','admin'),async(req,res)=>{const n=db.prepare("SELECT id FROM notifications WHERE id=? AND status IN ('Failed','Skipped')").get(req.params.id);if(!n)return res.status(404).json({error:'Notification not found'});db.prepare("UPDATE notifications SET status='Queued' WHERE id=?").run(n.id);await dispatchNotification(n.id);res.json({ok:true});});
app.post('/api/admin/notifications/process',auth,requireRole('superadmin','admin'),async(req,res)=>{const rows=db.prepare("SELECT id FROM notifications WHERE status='Queued' AND channel!='in-app' ORDER BY id LIMIT 50").all();for(const r of rows)await dispatchNotification(r.id);res.json({processed:rows.length});});
app.post('/api/ai/chat',aiLimiter,async(req,res)=>{const message=String(req.body.message||'').trim();if(!message)return res.status(400).json({error:'Message required'});const a=await aiAnswer(message);db.prepare('INSERT INTO chat_logs(session_id,user_message,assistant_message,provider) VALUES(?,?,?,?)').run(req.body.session_id||'',message,a.text,a.provider);res.json(a)});

app.use((err,req,res,next)=>{if(err?.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'ፋይሉ ከተፈቀደው መጠን በላይ ነው'});if(err?.name==='MulterError')return res.status(400).json({error:'የፋይል ጭነት ስህተት'});console.error(err);res.status(500).json({error:'Internal server error'});});

app.get('/admin',(req,res)=>res.sendFile(path.resolve('public/admin/index.html')));
if (JWT_SECRET === 'dev-secret-change-me') console.warn('WARNING: Set a strong JWT_SECRET in production.');
const server=app.listen(PORT,()=>console.log(`Digital Mesob running at http://localhost:${PORT}`));
process.on('SIGTERM',()=>server.close(()=>process.exit(0)));
process.on('SIGINT',()=>server.close(()=>process.exit(0)));
